### ISSUE TITLE
Automatically checks for private and public view

### ISSUE THREAD

**Issue by davidpham87** [MariusWirtz/TM1py#10]
Hello,

I think it would be a great addition to check private and public views when the user ask if a view exists. Moreover, I would prefer having the private argument True by default.

**Comment by MariusWirtz** [comment]
Hi,

are you suggesting that the function returns two booleans instead?
like:
view_exists_as_private, view_exists_as_public = tm1.view_exists('cube1', 'view1')

Yes. I suppose from user's perspectives thats more desirable. Lets change it.
