### ISSUE TITLE
Improvment of View*Selection

### ISSUE THREAD

**Issue by davidpham87** [MariusWirtz/TM1py#13]
Hello,

In the _construct_body method, one does type dispatching base on type. First of all, one should switch the order of verification as an AnnonymousSubset is a subset and that the pythonic way should use the `isinstance` function.

But to respect the OOP approach about type dispatching, the method should be defined within each Subset classes and called by the View*Selection.

**Comment by MariusWirtz** [comment]
Thanks for the finding! Its refactorred now.
