### ISSUE TITLE
logout

### ISSUE THREAD

**Issue by vicmora** [MariusWirtz/TM1py#15]
not sure if this matters but why is the logout method a post and not a get?

**Comment by MariusWirtz** [comment]
Hi,
the logout is implemented as an OData Action. OData Actions always require POST.

**Comment by vicmora** [comment]
makes sense, it was just something i saw in the documentation:

https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/W181f1083f3dd_455f_b2f8_f63c4a9c8010/page/HTTP%20authentication%20modes

**Comment by MariusWirtz** [comment]
Interesting. logout with GET works too!
