### ISSUE TITLE
help: first time use

### ISSUE THREAD

**Issue by charleshjw** [MariusWirtz/TM1py#5]
I copied the TM1py.py file to project folder. But I got following errors when running the code. Can someone help me understand the issue and how to fix it? Thank you.
---

from TM1py import TM1pyQueries as TM1

  File "TM1py.py", line 295
    ´cube_name´: String
                       ^
SyntaxError: Non-ASCII character '\xc2' in file TM1py.py on line 296, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by MariusWirtz** [comment]
are you using a Python version lower than 3? TM1py is written for python 3. If you use an earlier version it won't run. 

If you do use Python 3 try to add this

# -*- coding: utf-8 -*-

to the top of your script.
