### ISSUE TITLE
No issue

### ISSUE THREAD

**Issue by vizel** [MariusWirtz/TM1py#6]
Hi Marius,

a very nice python wrapper for the TM1-Rest-API you have developed so far! :) Thank you for the share!

I have a question (is where any other place than here to dump comments?) regarding your usage of TM1py. Do you use it productively for some tm1 model buildings for your work already? 

Is there any documentation which resources can be adressed with the TM1-Rest-API and how they can be used to contribute/complement code to your project?

Thank you in advance,
Timo

**Comment by MariusWirtz** [comment]
Hi Timo,

thank you. 

I think this is a good place to discuss about TM1py.
Yeah definetely, I used it productively to handle CellAnnotations and Processes. Also we use it to read and write data from cubes.

Yes there is. Check out this call against the metadata overview.
- http://localhost:8001/api/v1/$metadata
Maybe you also want to set up swagger-ui on your model. Its really helpful. Here is how. 
-> https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/W181f1083f3dd_455f_b2f8_f63c4a9c8010/page/Using%20swagger-ui%20with%20TM1%20server's,%20OData%20compliant,%20RESTful%20API

I would be more than happy if you contributed to our project.

Cheers,

Marius

**Comment by iamambrus** [comment]
FYI you can use http://swagger-ui.cubeac.com/
